services:
  server:
    container_name: llm-api
    image: ${DOCKER_IMAGE:-llm-api:local}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENABLE_INSTRUMENTATION=true
      - ALLOY_HOST=host.docker.internal
      - SERVICE_NAME=llm-api
      - PHOENIX_COLLECTOR_ENDPOINT=http://host.docker.internal:4318/v1/traces
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PHOENIX_API_KEY=${PHOENIX_API_KEY}
      - DB_HOST=100.95.50.80
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret123
      - DB_NAME=mydb
      - DB_VECTOR_HOST=100.95.50.80
      - DB_VECTOR_PORT=5433
      - DB_VECTOR_USER=pgvector
      - DB_VECTOR_PASSWORD=Test1234
      - DB_VECTOR_NAME=mydb
    ports:
      - "10000:10000"
